project: selva-project
buckets:
  - name: logs
    prefix: SELVA-logs
    iam_role_name: writer-role-logs
    write_prefix: FOOBAR/logs/
  - name: data
    prefix: SELVA-data
    iam_role_name: writer-role-data
    write_prefix: FOOBAR/data/